spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyserving?serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    cn.ruanduo98.easyserving.*: debug
  file:
    name: log/EasyServing-dev.log
    max-history: 30